const fs = require('fs-extra');
const path = require('path');
const { execSync } = require('child_process');

// Usage: npm run eject <tool-name> <new-client-repo-name>
const args = process.argv.slice(2);
if (args.length < 2) {
  console.error('❌ Usage: npm run eject <tool-folder-name> <new-client-repo-name>');
  process.exit(1);
}

const [toolName, clientRepoName] = args;
const sourceDir = path.join(__dirname, '../apps', toolName);
const targetDir = path.join(__dirname, '../../', clientRepoName); // Creates as sibling to this repo

console.log(`🚀 Preparing to eject '${toolName}' to '${targetDir}'...`);

if (!fs.existsSync(sourceDir)) {
  console.error(`❌ Error: Tool '${toolName}' not found in /apps.`);
  process.exit(1);
}

try {
  // 1. Copy the folder
  fs.copySync(sourceDir, targetDir);
  console.log('✅ Files copied.');

  // 2. Clean up ResultantAI specific files (optional)
  // Example: Remove internal config if it exists
  const internalConfig = path.join(targetDir, 'resultantai.internal.config.js');
  if (fs.existsSync(internalConfig)) {
    fs.removeSync(internalConfig);
    console.log('🧹 Internal configs removed.');
  }

  // 3. Initialize fresh Git repo
  execSync('git init', { cwd: targetDir });
  console.log('📦 New Git repository initialized.');

  // 4. Create a generic client README (Replace the internal context one)
  const clientReadme = `# ${clientRepoName}\n\nGenerated by ResultantAI.\n\n## Getting Started\nOpen index.html to view the tool.`;
  fs.writeFileSync(path.join(targetDir, 'README.md'), clientReadme);
  console.log('📄 Client-facing README generated.');

  console.log(`\n🎉 Ejection Complete! Your new client product is ready at:\n${targetDir}`);

} catch (err) {
  console.error('❌ Ejection failed:', err);
}
